- !!net.sourceforge.marathon.objectmap.OMapComponent
    componentRecognitionProperties:
    - {method: equals, name: name, value: OptionPane.button}
    - {method: equals, name: type, value: JButton}
    generalProperties:
    - {name: fieldName, value: defaultButton}
    - {name: component.class.simpleName, value: JButton}
    - {name: type, value: JButton}
    - {name: enabled, value: 'true'}
    - {name: indexOfType, value: '0'}
    - {name: instanceOf, value: javax.swing.JButton}
    - {name: actionCommand, value: OK}
    - {name: component.class.name, value: javax.swing.JButton}
    - {name: buttonText, value: OK}
    - {name: cText, value: OK}
    - {name: accessibleContext.accessibleName, value: OK}
    - {name: size, value: '[width=79,height=29]'}
    - {name: name, value: OptionPane.button}
    - {name: accessibleName, value: OK}
    - {name: position, value: '[x=529,y=428]'}
    name: OK
- !!net.sourceforge.marathon.objectmap.OMapComponent
    componentRecognitionProperties:
    - {method: equals, name: type, value: JPanel}
    - {method: equals, name: indexOfType, value: '3'}
    generalProperties:
    - {name: component.class.simpleName, value: JPanel}
    - {name: type, value: JPanel}
    - {name: indexOfType, value: '3'}
    - {name: enabled, value: 'true'}
    - {name: instanceOf, value: javax.swing.JPanel}
    - {name: component.class.name, value: javax.swing.JPanel}
    - {name: size, value: '[width=313,height=74]'}
    - {name: position, value: '[x=295,y=341]'}
    name: JPanel_3
- !!net.sourceforge.marathon.objectmap.OMapComponent
    componentRecognitionProperties:
    - {method: equals, name: type, value: JOptionPane}
    - {method: equals, name: indexOfType, value: '0'}
    generalProperties:
    - {name: component.class.simpleName, value: JOptionPane}
    - {name: type, value: JOptionPane}
    - {name: indexOfType, value: '0'}
    - {name: enabled, value: 'true'}
    - {name: instanceOf, value: javax.swing.JOptionPane}
    - {name: component.class.name, value: javax.swing.JOptionPane}
    - {name: size, value: '[width=452,height=145]'}
    - {name: position, value: '[x=177,y=329]'}
    name: JOptionPane_0
- !!net.sourceforge.marathon.objectmap.OMapComponent
    componentRecognitionProperties:
    - {method: equals, name: type, value: JPanel}
    - {method: equals, name: indexOfType, value: '2'}
    generalProperties:
    - {name: component.class.simpleName, value: JPanel}
    - {name: type, value: JPanel}
    - {name: indexOfType, value: '2'}
    - {name: enabled, value: 'true'}
    - {name: instanceOf, value: javax.swing.JPanel}
    - {name: component.class.name, value: javax.swing.JPanel}
    - {name: size, value: '[width=74,height=74]'}
    - {name: position, value: '[x=177,y=341]'}
    name: JPanel_2
